language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.email "dsampy@gmail.com"
- git config --global user.name "Travis-CI"
script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://dsampy:${GH_TOKEN}:@github.com" > .git/credentials
- rake travis
branches:
  only:
  - master
env:
  global:
    secure: Qg8PyQrx1OUAv8uKQhg51dYMt1waUjeSMPLgvkjRCYTKmdhX8Ag+ttKbb5YspkWeJ1mFr0+EQ0ut6mRAZPIXuv+0jFC7zPHnQ5pYDx68uZ3Y1Dxgv99NPklnpOyXy8pVw8LCDgAIwl00y+MEpjdmCrnqmFXYrMgmRQM6P5oSDOk=
